name: Nodejs App
on:
  push:
    branches:
      - main

jobs:
  main:
    # self-hosted
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.9.0] #指定node版本
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # 由于网路情况，很容易超时，设置为60s
          connect_timeout: 60s
          # 将工作目录下的文件全部拷贝到自己服务器的工作目录
          scp: |
            ./* => /www/github-action-node
          # 完成拷贝后在服务器执行的脚本
          last_ssh: |
            cd /www/github-action-node
            pnpm i
            pm2 start
