name: Nodejs App
on:
  push:
    branches:
      - main

jobs:
  main:
    # self-hosted
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # 由于网路情况，很容易超时，设置为60s
          connect_timeout: 60s
          scp: |
            ./* => /www/github-action-node
          last_ssh: |
            cd ${{ secrets.TARGET_DIR }}
            pnpm i
            pm2 start
